[package]
name = "meshless_voronoi"
description = "An implementation of the Meshless Voronoi algorithm in rust."
version = "0.3.2"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yuyttenhove/meshless_voro"
keywords = ["voronoi","graphics","diagram"]
categories = ["graphics","science", "mathematics"]
exclude = ["plot_vortess.py"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.23"
rstar = "0.10"
rayon = { version = "1.7", optional = true }
hdf5 = { version = "0.8", optional = true }

[features]
rayon = ["dep:rayon"]
hdf5 = ["dep:hdf5"]

[dev-dependencies]
rand = "0.8"
float-cmp = "0.9"